import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import type { FeatureContext, FeatureModule, GeneratedFile } from "@pilotevent/plugin-api";
import Handlebars from "handlebars";
import { z } from "zod";

import { OUTBOX_MIGRATION_SQL } from "./migration-sql.js";

const templatesDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "templates");

const outboxConfigSchema = z.object({
  enabled: z.boolean().default(true),
  store: z.string().min(1).default("postgres"),
});

const SUPPORTED_LANGUAGES = new Set(["node-ts"]);
const HEADER =
  "// Generated by EventPilot (feature: outbox). Re-run `eventpilot generate --force` to overwrite.\n\n";

function compile(templateFile: string) {
  return Handlebars.compile(readFileSync(path.join(templatesDir, templateFile), "utf-8"));
}

export const outboxFeature: FeatureModule = {
  id: "outbox",
  configSchema: outboxConfigSchema,

  async apply(ctx: FeatureContext): Promise<GeneratedFile[]> {
    outboxConfigSchema.parse(ctx.config ?? {});

    const producers = ctx.services.filter((service) => service.produces.length > 0);

    const unsupported = producers.filter((service) => !SUPPORTED_LANGUAGES.has(service.language));
    if (unsupported.length > 0) {
      const names = unsupported.map((s) => `${s.name} (${s.language})`).join(", ");
      throw new Error(
        `feature-outbox doesn't support: ${names}. Supported languages: ${[...SUPPORTED_LANGUAGES].join(", ")}.`,
      );
    }

    const outboxContent = HEADER + compile("outbox.ts.hbs")({ migrationSql: OUTBOX_MIGRATION_SQL });

    return producers.flatMap((service) => {
      const base = `${ctx.outputDir}/${service.name}/src`;
      return [
        { path: `${base}/outbox.ts`, content: outboxContent },
        {
          path: `${base}/outbox-relay.ts`,
          content: HEADER + compile("outbox-relay.ts.hbs")({ service }),
        },
      ];
    });
  },
};
