import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import type { GenerateContext, GeneratedFile, LanguageGenerator } from "@pilotevent/plugin-api";

import { Handlebars, pascalCase } from "./handlebars-helpers.js";

const templatesDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "templates");

const GENERATED_HEADER =
  "// Generated by EventPilot. Re-run `eventpilot generate --force` to overwrite.\n\n";

function compile(templateFile: string): HandlebarsTemplateDelegate {
  const source = readFileSync(path.join(templatesDir, templateFile), "utf-8");
  return Handlebars.compile(source);
}

export const javaGenerator: LanguageGenerator = {
  id: "java",

  async generate(ctx: GenerateContext): Promise<GeneratedFile[]> {
    const base = `${ctx.outputDir}/${ctx.service.name}`;
    const dlq = ctx.features?.dlq;
    const data = {
      projectName: ctx.projectName,
      service: ctx.service,
      dlq: Boolean(dlq),
      outbox: Boolean(ctx.features?.outbox),
    };
    const javaDir = `${base}/src/main/java/com/eventpilot/generated`;

    return [
      { path: `${base}/build.gradle`, content: compile("build.gradle.hbs")(data) },
      { path: `${base}/settings.gradle`, content: compile("settings.gradle.hbs")(data) },
      {
        path: `${javaDir}/${pascalCase(ctx.service.name)}Producer.java`,
        content: GENERATED_HEADER + compile("Producer.java.hbs")(data),
      },
      {
        path: `${javaDir}/${pascalCase(ctx.service.name)}Consumer.java`,
        content: GENERATED_HEADER + compile("Consumer.java.hbs")(data),
      },
      {
        path: `${javaDir}/${pascalCase(ctx.service.name)}Main.java`,
        content: GENERATED_HEADER + compile("Main.java.hbs")(data),
      },
      {
        path: `${javaDir}/EventPilotAgent.java`,
        content: GENERATED_HEADER + compile("EventPilotAgent.java.hbs")(data),
      },
    ];
  },
};
