import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import type { FeatureContext, FeatureModule, GeneratedFile } from "@eventpilot/plugin-api";
import Handlebars from "handlebars";
import { z } from "zod";

const templatesDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "templates");

const dlqConfigSchema = z.object({
  maxRetries: z.number().int().nonnegative().default(5),
  backoff: z.enum(["fixed", "exponential"]).default("exponential"),
});

const SUPPORTED_LANGUAGES = new Set(["node-ts"]);

export const dlqFeature: FeatureModule = {
  id: "dlq",
  configSchema: dlqConfigSchema,

  async apply(ctx: FeatureContext): Promise<GeneratedFile[]> {
    const config = dlqConfigSchema.parse(ctx.config ?? {});

    const unsupported = ctx.services.filter(
      (service) => !SUPPORTED_LANGUAGES.has(service.language),
    );
    if (unsupported.length > 0) {
      const names = unsupported.map((s) => `${s.name} (${s.language})`).join(", ");
      throw new Error(
        `feature-dlq doesn't support: ${names}. Supported languages: ${[...SUPPORTED_LANGUAGES].join(", ")}.`,
      );
    }

    const template = Handlebars.compile(
      readFileSync(path.join(templatesDir, "dlq.ts.hbs"), "utf-8"),
    );
    const content =
      "// Generated by EventPilot (feature: dlq). Re-run `eventpilot generate --force` to overwrite.\n\n" +
      template(config);

    return ctx.services.map((service) => ({
      path: `${ctx.outputDir}/${service.name}/src/dlq.ts`,
      content,
    }));
  },
};
