import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import type {
  FeatureContext,
  FeatureModule,
  GeneratedFile,
  ServiceSpec,
} from "@pilotevent/plugin-api";
import Handlebars from "handlebars";
import { z } from "zod";

const templatesDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "templates");
const HEADER =
  "// Generated by EventPilot (feature: dlq). Re-run `eventpilot generate --force` to overwrite.\n\n";

const dlqConfigSchema = z.object({
  maxRetries: z.number().int().nonnegative().default(5),
  backoff: z.enum(["fixed", "exponential"]).default("exponential"),
});

const SUPPORTED_LANGUAGES = new Set(["node-ts", "java"]);

function compile(templateFile: string) {
  return Handlebars.compile(readFileSync(path.join(templatesDir, templateFile), "utf-8"));
}

function fileFor(
  outputDir: string,
  service: ServiceSpec,
  config: Record<string, unknown>,
): GeneratedFile {
  if (service.language === "java") {
    return {
      path: `${outputDir}/${service.name}/src/main/java/com/eventpilot/generated/Dlq.java`,
      content: HEADER + compile("Dlq.java.hbs")(config),
    };
  }
  return {
    path: `${outputDir}/${service.name}/src/dlq.ts`,
    content: HEADER + compile("dlq.ts.hbs")(config),
  };
}

export const dlqFeature: FeatureModule = {
  id: "dlq",
  configSchema: dlqConfigSchema,

  async apply(ctx: FeatureContext): Promise<GeneratedFile[]> {
    const config = dlqConfigSchema.parse(ctx.config ?? {});

    // Only consumers need the retry/DLQ helper — a pure producer in an
    // unsupported language shouldn't block the whole project from using it.
    const consumers = ctx.services.filter((service) => service.consumes.length > 0);

    const unsupported = consumers.filter((service) => !SUPPORTED_LANGUAGES.has(service.language));
    if (unsupported.length > 0) {
      const names = unsupported.map((s) => `${s.name} (${s.language})`).join(", ");
      throw new Error(
        `feature-dlq doesn't support: ${names}. Supported languages: ${[...SUPPORTED_LANGUAGES].join(", ")}.`,
      );
    }

    return consumers.map((service) => fileFor(ctx.outputDir, service, config));
  },
};
