// Generated by EventPilot. Re-run `eventpilot generate --force` to overwrite.

import { createEventPilotAgent } from "@pilotevent/sdk-node";
import { Kafka, type EachMessagePayload } from "kafkajs";
import { withDlq } from "./dlq.js";

export interface OrderServiceMessageHeaders {
  correlationId?: string;
  causationId?: string;
}

export interface OrderServiceConsumerOptions {
  brokers: string[];
  groupId?: string;
  onMessage: (
    topic: string,
    payload: unknown,
    headers: OrderServiceMessageHeaders,
  ) => Promise<void> | void;
}

export function createOrderServiceConsumer(options: OrderServiceConsumerOptions) {
  const kafka = new Kafka({ clientId: "order-service", brokers: options.brokers });
  const agent = createEventPilotAgent({ service: "order-service" });
  const consumer = agent.wrapConsumer(
    kafka.consumer({ groupId: options.groupId ?? "order-service" }),
  );
  const dlqProducer = kafka.producer();

  const topics = ["payment.confirmed"];

  return {
    async start(): Promise<void> {
      await consumer.connect();
      await dlqProducer.connect();
      for (const topic of topics) {
        await consumer.subscribe({ topic, fromBeginning: false });
      }
      await consumer.run({
        eachMessage: async ({ topic, message }: EachMessagePayload) => {
          const payload = message.value ? JSON.parse(message.value.toString()) : null;
          const headers = {
            correlationId: message.headers?.["x-correlation-id"]?.toString(),
            causationId: message.headers?.["x-causation-id"]?.toString(),
          };
          const guarded = withDlq(
            topic,
            dlqProducer,
            () => options.onMessage(topic, payload, headers),
            undefined,
            (err) => agent.reportError(topic, headers.correlationId ?? null, err),
          );
          await guarded(payload, {
            key: message.key?.toString() ?? null,
            value: message.value,
            headers: Object.fromEntries(
              Object.entries(message.headers ?? {}).map(([k, v]) => [k, v?.toString() ?? ""]),
            ),
          });
        },
      });
    },
    async stop(): Promise<void> {
      await consumer.disconnect();
      await dlqProducer.disconnect();
    },
  };
}
