// Generated by EventPilot. Re-run `eventpilot generate --force` to overwrite.

import { createOrderServiceProducer } from "./producer.js";
import { createOrderServiceConsumer } from "./consumer.js";

const brokers = (process.env.EVENTPILOT_BROKERS ?? "localhost:9092").split(",");

async function main(): Promise<void> {
  const producer = createOrderServiceProducer({ brokers });
  await producer.connect();

  const consumer = createOrderServiceConsumer({
    brokers,
    onMessage: async (topic, payload, headers) => {
      console.log(`[order-service] received on ${topic}`, payload, headers);
    },
  });
  await consumer.start();

  console.log(
    "order-service is running. produces=[order.created,order.cancelled] consumes=[payment.confirmed]",
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
