// Generated by EventPilot (feature: outbox). Re-run `eventpilot generate --force` to overwrite.

import { Kafka } from "kafkajs";
import { Pool } from "pg";

export interface OutboxRelayOptions {
  brokers: string[];
  connectionString: string;
  pollIntervalMs?: number;
  batchSize?: number;
}

export interface OutboxRelay {
  stop(): void;
  done: Promise<void>;
}

/**
 * Polls the outbox table for unpublished rows and delivers them to the
 * broker. Run one of these per service alongside its producer/consumer —
 * this is what actually gets events out of the outbox table written by
 * `writeOutbox` (outbox.ts) and onto the broker.
 */
export function startOutboxRelay(options: OutboxRelayOptions): OutboxRelay {
  const pool = new Pool({ connectionString: options.connectionString });
  const kafka = new Kafka({ clientId: "order-service-outbox-relay", brokers: options.brokers });
  const producer = kafka.producer();
  const pollIntervalMs = options.pollIntervalMs ?? 1000;
  const batchSize = options.batchSize ?? 50;

  let stopped = false;

  async function tick(): Promise<void> {
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      const { rows } = await client.query(
        "SELECT * FROM outbox WHERE published_at IS NULL ORDER BY id LIMIT $1 FOR UPDATE SKIP LOCKED",
        [batchSize],
      );

      for (const row of rows) {
        await producer.send({
          topic: row.topic,
          messages: [
            {
              key: row.key ?? undefined,
              value: JSON.stringify(row.payload),
              headers: {
                ...row.headers,
                ...(row.correlation_id ? { "x-correlation-id": row.correlation_id } : {}),
                ...(row.causation_id ? { "x-causation-id": row.causation_id } : {}),
              },
            },
          ],
        });
        await client.query("UPDATE outbox SET published_at = now() WHERE id = $1", [row.id]);
      }

      await client.query("COMMIT");
    } catch (err) {
      await client.query("ROLLBACK");
      throw err;
    } finally {
      client.release();
    }
  }

  async function loop(): Promise<void> {
    await producer.connect();
    while (!stopped) {
      try {
        await tick();
      } catch (err) {
        console.error("outbox relay tick failed:", err);
      }
      await new Promise((resolve) => setTimeout(resolve, pollIntervalMs));
    }
    await producer.disconnect();
    await pool.end();
  }

  const done = loop();

  return {
    stop(): void {
      stopped = true;
    },
    done,
  };
}
