// Generated by EventPilot. Re-run `eventpilot generate --force` to overwrite.

import { createEventPilotAgent } from "@pilotevent/sdk-node";
import { Kafka } from "kafkajs";

export interface OrderServiceProducerOptions {
  brokers: string[];
}

export function createOrderServiceProducer(options: OrderServiceProducerOptions) {
  const kafka = new Kafka({ clientId: "order-service", brokers: options.brokers });
  const agent = createEventPilotAgent({ service: "order-service" });
  const producer = agent.wrapProducer(kafka.producer());

  return {
    async connect(): Promise<void> {
      await producer.connect();
    },
    async disconnect(): Promise<void> {
      await producer.disconnect();
    },
    async publishOrderCreated(
      payload: unknown,
      correlationId?: string,
      causationId?: string,
    ): Promise<void> {
      await producer.send({
        topic: "order.created",
        messages: [
          {
            value: JSON.stringify(payload),
            headers: {
              ...(correlationId ? { "x-correlation-id": correlationId } : {}),
              ...(causationId ? { "x-causation-id": causationId } : {}),
            },
          },
        ],
      });
    },
    async publishOrderCancelled(
      payload: unknown,
      correlationId?: string,
      causationId?: string,
    ): Promise<void> {
      await producer.send({
        topic: "order.cancelled",
        messages: [
          {
            value: JSON.stringify(payload),
            headers: {
              ...(correlationId ? { "x-correlation-id": correlationId } : {}),
              ...(causationId ? { "x-causation-id": causationId } : {}),
            },
          },
        ],
      });
    },
  };
}
