import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import type { GenerateContext, GeneratedFile, LanguageGenerator } from "@eventpilot/plugin-api";

import { Handlebars } from "./handlebars-helpers.js";

const templatesDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "templates");

const GENERATED_HEADER =
  "// Generated by EventPilot. Re-run `eventpilot generate --force` to overwrite.\n\n";

function compile(templateFile: string): HandlebarsTemplateDelegate {
  const source = readFileSync(path.join(templatesDir, templateFile), "utf-8");
  return Handlebars.compile(source);
}

export const nodeTsGenerator: LanguageGenerator = {
  id: "node-ts",

  async generate(ctx: GenerateContext): Promise<GeneratedFile[]> {
    const base = `${ctx.outputDir}/${ctx.service.name}`;
    const data = { projectName: ctx.projectName, service: ctx.service };

    return [
      {
        path: `${base}/src/producer.ts`,
        content: GENERATED_HEADER + compile("producer.ts.hbs")(data),
      },
      {
        path: `${base}/src/consumer.ts`,
        content: GENERATED_HEADER + compile("consumer.ts.hbs")(data),
      },
      { path: `${base}/src/index.ts`, content: GENERATED_HEADER + compile("index.ts.hbs")(data) },
      { path: `${base}/package.json`, content: compile("package.json.hbs")(data) },
      { path: `${base}/tsconfig.json`, content: compile("tsconfig.json.hbs")(data) },
    ];
  },
};
