services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: eventpilot-redpanda
    command:
      - redpanda
      - start
      - --mode
      - dev-container
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://localhost:9092
      - --pandaproxy-addr
      - 0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - localhost:8082
      - --schema-registry-addr
      - 0.0.0.0:8081
    ports:
      - 9092:9092
      - 8081:8081
      - 8082:8082
      - 9644:9644
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.7.2
    container_name: eventpilot-console
    depends_on:
      - redpanda
    ports:
      - 8080:8080
    environment:
      KAFKA_BROKERS: redpanda:9092
  postgres:
    image: postgres:16-alpine
    container_name: eventpilot-postgres
    environment:
      POSTGRES_USER: eventpilot
      POSTGRES_PASSWORD: eventpilot
      POSTGRES_DB: eventpilot
    ports:
      - 5432:5432
    volumes:
      - eventpilot-postgres-data:/var/lib/postgresql/data
volumes:
  eventpilot-postgres-data: {}
